### ISSUE TITLE
Some rounded endings are much more “squared” than others

### ISSUE THREAD

**Issue by tphinney** [TaVaTake/madimi#10]
When I look at glyphs such as C c and G, I have noticed that one of the two rounded stroke endings is much more square-ish than the other. In these cases the lower one. I don’t see the same sort of thing in E L J j S s.

Madimi is a fairly organic, slightly irregular typeface, so this can totally be just “yes, the typeface has that kind of almost random variation between some letters!” However, it might also be the case that maybe just the occasional stroke ending is a bit more square-ish than you intend, so I thought I should check.  :)

**Comment by tphinney** [comment]
Which was the answer?

**Comment by LauraMeseguer** [comment]
hello! this has been a recurrent feature in this typeface, is it finished now?

**Comment by bghryct** [comment]
I believe it's completed but I'll leave the final decision to @TaVaTake

**Comment by bghryct** [comment]
@tphinney I think that the answer is that they're slightly inconsistent but have been refined.

**Comment by TaVaTake** [comment]
True, I have refined them a little more now and will finalise them tonight. Thank you all for the support throughout this project. :)
