### ISSUE TITLE
space character is too narrow

### ISSUE THREAD

**Issue by tphinney** [TaVaTake/madimi#6]
Besides spacing in general needing work, the space character is definitely too narrow. As a starting point, try making it the same width as the lowercase “i” (and if that gets wider, do the same with the space). If I recall correctly that would increase from 200 to 280 as a start.

**Comment by TaVaTake** [comment]
thank you, I have made changes to that :)

**Comment by tphinney** [comment]
I see this went from 200 to 218. I might humbly suggest just another 20 units would be good.
