### ISSUE TITLE
Spacing consistency needs work

### ISSUE THREAD

**Issue by tphinney** [TaVaTake/madimi#7]
FIRST all this is dependent on the cap spacing being right. I think it is probably a bit loose overall, still. So you could drop ALL the numbers I say below, by maybe 10%? But if I were to go with the base cap-straight spacing you have, I think this....

Cap spacing currently seems to be:
- 79 straight caps
- 60 for M, U and left side of N (but 79 for right side of N)
- 57 for O and similar characters

I think that you could reduce the O and similar characters another five units or so. (Assuming you keep the straights as is).

Given their shapes, M and U and N and similar characters should be about 80% of the way from the round character spacing to the straight spacing. So more like 70–75 than 60.

Currently, the lowercase straight sidebearing is 60, so about 3/4 of the cap. But it should be more than 90% of the cap. Like if the cap is 79, do 73 or something. Or if you reduce the cap straight to 72, then do 65. Then do the lowercase rounds at maybe 61 or 62.

**Comment by tphinney** [comment]
So what I would suggest is:
- 72 straight caps H etc
- 67 M U N 
- 48 O and left side of C
- 65 straight lowercase
- 61 m u n
- 43 o and left side of c

**Comment by tphinney** [comment]
Perhaps if the person who filed the issue is “internal” it is good to let them close it when they think it is done. If you give me appropriate permissions in the repo, I could do that.

In this case, it looks like you didn’t quite follow all the discussion. Just treat the second comment as the final one. 😬

Unless of course you disagree—in which case we should discuss it further.

**Comment by tphinney** [comment]
Looks much better. I see you went even tighter on the lowercase rounds (o, c), though... maybe a bit too tight, given the other spacing?

**Comment by bghryct** [comment]
kerned for now.
