### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by LisaHuang2017** [TaVaTake/madimi#8]
These are comments based on the Glyphs files of Madimi from Jan 04, 2024.

[Madimi_fb_Lisa_060124.pdf](https://github.com/TaVaTake/madimi/files/13850742/Madimi_fb_Lisa_060124.pdf)

Uppercase:
- [x] R = top and bottom counters need to be better balanced by lowering the middle part a little
- [x] W = looks too back slanted, it can be solved by pulling the bottom parts to the left
- [x] Y = maybe another Y?
- [x] ligature IJ = these need to be closer together because it is a digraph. Maybe it needs a different design of J?
- [x] Thorn = the belly needs to be bigger

Lowercase: 
- [x] y = same as the capital variant
- [x] germandbls = this is an old construction of that glyph. You can check out how it is designed in other typefaces for a more modern reference 

Figures:
- [x] 3 = its top should be slightly wider and the middle part a bit shorter
- [x] 4 = the horizontal stroke could be lower for a better balance

- [x] ? = could be more simple
- [x] asterisk = too big and horizontal arms are too high

Spacing:
This is mentioned in another issue #7

**Comment by LauraMeseguer** [comment]
About the Y (and y)
I have been suggesting @TaVaTake to create a set of Alternative Characters, she needs to take the decision
About the rest, I think lowering the bar in 4 can be tricky, but give it a try :)

**Comment by TaVaTake** [comment]
Thank you all for the amazing feedback. I will have started implementing some changes as suggested. Thank you for the suggestion for alternative characters but as mentioned, I will for this particular project only create whats only needed in Latin Core character set considering the limited time frame.
