### ISSUE TITLE
Diacritic shapes and positions

### ISSUE THREAD

**Issue by LisaHuang2017** [TaVaTake/madimi#9]
These are comments based on the Glyphs file of Madimi from Jan 4, 2024.

[Madimi_fb_Lisa_060124.pdf](https://github.com/TaVaTake/madimi/files/13850799/Madimi_fb_Lisa_060124.pdf)

- [x] Alignment with each other: they need to look more aligned on the same level (for example: breve, macron and dieresis are too low, circumflex and tilde too high)
- [x] Some diacritics are too wide: breve and circumflex are way too wide, they need to be visually of about the same width as acute or dieresis
- [x] tilde = it has to be more like a wave. Look at how it is designed on other typefaces for a better idea
- [x] ogonek = this has to look like "a hair growing" from the bottom right part of the letter
- [x] cedilla = it has to look more like a hook, with the connection segment on its top center
- [x] Lcaron = the commaaccent is too far from the letter. It has to be "inside" the letter
- [x] dots on lowercase = make sure that the dot on iogonek is the same as in default i

**Comment by LauraMeseguer** [comment]
@TaVaTake do you think you will have these changes done for tomorrow's feedback session?
Thanks @LisaHuang2017, this is great 

1. About the alignment, there are different formulas, but it case you get lost, try central alignment, first and try to keep the same visual space between the character and the diacritics
2. Right, try to balance the color
3. Agree, always have a look to other typefaces
4. in letter u needs to be centered
5. Agree, have a look to other typefaces
6. Agree
7. Agree

**Comment by tphinney** [comment]
I don’t see any checking off of these issues, or comments/responses, but I think @TaVaTake has addressed most of them?

The remaining diacritic things that leap out at me:
- [x] the ogonek shape could be just a bit less “drooping” perhaps? Although the “a” and “g” are quite open, so it does not need to curve back up as much as one usually expects. But maybe just end more horozontally or with a tiny bit of upcurve.
- [x] the acute and grave are too centered on the whole accent; acute anchor could move 15-20 units left, grave anchor could move 15-20 right (which would make the composed diacritics shift in the opposite direction).
- [x] conversely, commaaccent has the opposite problem! It is centered on JUST the top part of the diacritic, but could be more centered on the whole thing. Currently it feels too far to the left, so move the anchor a bit left so it shifts right.

**Comment by bghryct** [comment]
done
